# Generated by Django 3.2 on 2022-11-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('equipo', models.CharField(max_length=50, verbose_name='Equipo')),
            ],
        ),
    ]
