# Generated by Django 3.2 on 2022-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(default='null', upload_to='media/imagenes_perfil/'),
        ),
    ]
