# Generated by Django 3.2 on 2022-11-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('teléfono', models.IntegerField(verbose_name='Teléfono')),
                ('ubicacion', models.URLField(verbose_name='Ubicación')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol5.equipo'),
        ),
    ]
