# Generated by Django 3.2 on 2022-12-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol5', '0002_jugador_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancha',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
